### ISSUE TITLE
CLEARTEXT communication to open.bmob.cn not permitted by network security policy

### ISSUE THREAD

**Issue by jyygithub** [bmob/bmob-android-sdk#28]
CLEARTEXT communication to open.bmob.cn not permitted by network security policy

**Comment by jbozic1** [comment]
Add one line to your manifest application tag
   <application
        android:name=".App"
        ----
        **android:usesCleartextTraffic="true"**
       .....
>

**Comment by chaozhouzhang** [comment]
已适配android9.0网络明文请求。
