### ISSUE TITLE
导包出错……

### ISSUE THREAD

**Issue by zxj5470** [bmob/bmob-android-sdk#8]
使用gradle方式和使用本地libs方式添加编译后程序直接无法运行。
手机版本小米5s plus（已关闭MIUI优化）
Android 7.0

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/PACKAGE-1/base.apk",
 zip file "/data/app/PACKAGE-1/split_lib_dependencies_apk.apk",
 zip file "/data/app/PACKAGE-1/split_lib_slice_0_apk.apk",
 zip file "/data/app/PACKAGE-1/split_lib_slice_1_apk.apk",
 zip file "/data/app/PACKAGE-1/split_lib_slice_2_apk.apk",
 zip file "/data/app/PACKAGE-1/split_lib_slice_3_apk.apk",
 zip file "/data/app/PACKAGE-1/split_lib_slice_4_apk.apk",
 zip file "/data/app/PACKAGE-1/split_lib_slice_5_apk.apk",
 zip file "/data/app/PACKAGE-1/split_lib_slice_6_apk.apk",
 zip file "/data/app/PACKAGE-1/split_lib_slice_7_apk.apk",
 zip file "/data/app/PACKAGE-1/split_lib_slice_8_apk.apk",
 zip file "/data/app/PACKAGE-1/split_lib_slice_9_apk.apk"],
nativeLibraryDirectories=[/data/app/PACKAGE-1/lib/arm64,
 /data/app/PACKAGE-1/base.apk!/lib/arm64-v8a,
 /data/app/PACKAGE-1/split_lib_dependencies_apk.apk!/lib/arm64-v8a,
 /data/app/PACKAGE-1/split_lib_slice_0_apk.apk!/lib/arm64-v8a,
 /data/app/PACKAGE-1/split_lib_slice_1_apk.apk!/lib/arm64-v8a,
 /data/app/PACKAGE-1/split_lib_slice_2_apk.apk!/lib/arm64-v8a,
 /data/app/PACKAGE-1/split_lib_slice_3_apk.apk!/lib/arm64-v8a,
 /data/app/PACKAGE-1/split_lib_slice_4_apk.apk!/lib/arm64-v8a,
 /data/app/PACKAGE-1/split_lib_slice_5_apk.apk!/lib/arm64-v8a,
 /data/app/PACKAGE-1/split_lib_slice_6_apk.apk!/lib/arm64-v8a,
 /data/app/PACKAGE-1/split_lib_slice_7_apk.apk!/lib/arm64-v8a,
 /data/app/PACKAGE-1/split_lib_slice_8_apk.apk!/lib/arm64-v8a,
 /data/app/PACKAGE-1/split_lib_slice_9_apk.apk!/lib/arm64-v8a,
 /system/lib64,
 /vendor/lib64]]] couldn't find "libruntimecore_java.so"

**Comment by Ni2014** [comment]
你好 请加q 1806559096 进一步沟通 看下是不是兼容性的问题 也顺便看下你用的数据sdk的版本 希望能一起把这个问题解决 因为看日志没看到sdk的日志信息 我这边也不好复现

**Comment by zxj5470** [comment]
问题已解决……原因是某第三方地图的jni疑似是32位。单独使用正常。
bmob单独开一个工程导包也正常。两个混合在一起后就导致32位和64位的NDK冲突了。
安卓系统的锅……混合之后安卓系统找不到上面要的arm64-v8a的对应的包。所以问题其实和bmob本身本关系。
build.gradle(app)
`ndk {
            abiFilters "armeabi-v7a", "arm64"
        }
`
gradle.properties
`android.useDeprecatedNdk=true`
解决
